AWSTemplateFormatVersion: '2010-09-09'
Description: 'Voice Mode - AWS Infrastructure (Lambda, API Gateway, DynamoDB, S3)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment

  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: API key for mobile app authentication
    MinLength: 32

Resources:
  # ============= S3 BUCKET =============
  VoiceModeAudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'voice-mode-audio-${AWS::AccountId}-${Environment}-${AWS::StackName}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldAudio
            Status: Enabled
            ExpirationInDays: 90
            Prefix: 'audio/'

  # ============= DYNAMODB TABLE =============
  TranscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'voice-mode-transcriptions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transcriptionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: transcriptionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdTimestampIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ============= IAM ROLE FOR LAMBDA =============
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: VoiceModeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt TranscriptionsTable.Arn
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource: !Sub '${TranscriptionsTable.Arn}/index/UserIdTimestampIndex'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub '${VoiceModeAudioBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'

  # ============= LAMBDA FUNCTION =============
  TranscribeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'voice-mode-transcribe-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Timeout: 300
      MemorySize: 1024
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TranscriptionsTable
          S3_BUCKET: !Ref VoiceModeAudioBucket
          ENVIRONMENT: !Ref Environment
          AWS_REGION: !Ref AWS::Region
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Lambda deployed successfully' }),
              headers: { 'Content-Type': 'application/json' }
            };
          };

  # ============= API GATEWAY =============
  VoiceModeApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'voice-mode-api-${Environment}'
      Description: Voice Mode API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VoiceModeApi
      ParentId: !GetAtt VoiceModeApi.RootResourceId
      PathPart: transcribe

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VoiceModeApi
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TranscribeFunction.Arn}/invocations'

  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: VoiceModeAuthorizer
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      AuthorizerCredentials: !GetAtt AuthorizerRole.Arn
      AuthorizerUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerFunction.Arn}/invocations'

  AuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt AuthorizerFunction.Arn

  AuthorizerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'voice-mode-authorizer-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          API_KEY: !Ref ApiKeyValue
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const apiKey = process.env.API_KEY;
            const token = event.authorizationToken;

            if (!token) {
              throw new Error('Unauthorized');
            }

            const parts = token.split(' ');
            if (parts.length !== 2 || parts[0] !== 'Bearer') {
              throw new Error('Unauthorized');
            }

            const key = parts[1];

            if (key !== apiKey) {
              throw new Error('Unauthorized');
            }

            return {
              principalId: 'user',
              policyDocument: {
                Version: '2012-10-17',
                Statement: [
                  {
                    Action: 'execute-api:Invoke',
                    Effect: 'Allow',
                    Resource: event.methodArn
                  }
                ]
              }
            };
          };

  LambdaPermissionForApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TranscribeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceModeApi}/*/*'

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref VoiceModeApi
      StageName: !Ref Environment

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${VoiceModeApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub 'VoiceMode-ApiEndpoint-${Environment}'

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt TranscribeFunction.Arn
    Export:
      Name: !Sub 'VoiceMode-Lambda-${Environment}'

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref TranscriptionsTable
    Export:
      Name: !Sub 'VoiceMode-Table-${Environment}'

  S3BucketName:
    Description: S3 bucket name
    Value: !Ref VoiceModeAudioBucket
    Export:
      Name: !Sub 'VoiceMode-Bucket-${Environment}'
